### PR TITLE
#511 fix the generated python step data record import statement

### LINKED ISSUE #511: BUG: When creating a project with both a Java and Python data delivery pipeline, as well as a custom record, the record import statement in the ingest_base.py has the incorrect name for the data records folder.
## Description
Found during regression test script development. When creating a project with both a Java and Python data delivery pipeline, as well as a custom record, the record import statement in the `ingest_base.py` file has the incorrect name for the data records folder.

## Steps to Reproduce
1. Navigate to the regression test script.
2. Follow the steps for Getting Started, Instantiating the Regression Test Project, and Adding Pipelines
3. On the second build utilizing mvn clean install, you will encounter an error:
`[ERROR] src/sync_py_spark_pipeline/generated/step/ingest_base.py:19:0: E0401: Unable to import 'regression_test_data_records.record.py_person' (import-error)`

## Expected Behavior
The build should pass and the proper import name should exist in the `ingest_base.py`.

## Actual Behavior
The build fails.

## Test Steps
Follow the `Steps to Reproduce` and verify you can successfully complete the build

### PR DESCRIPTION
**Pull request by csun-cpointe**

### CODE REVIEW

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java [hunk 1]
```diff
@@ -67,4 +76,55 @@ protected boolean shouldGenerateStep(Step step, GenerationContext generationCont
...
+                Node execution = executions.item(i);
+                if (execution.getNodeType() == Node.ELEMENT_NODE){
+                    configuration = getDataRecordConfiguration(execution);
+                    if (configuration != null) {
+                        break;
+                    }
+                }
+            }
+
+            if (configuration != null && configuration.getTextContent().contains("separate")) {
```
Comment (epwilkins) [inline foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java]: A: I think it would be more straight-forward to check for the module within `modules`. This is probably a sensible check anyway, as it would allow us to verify that the module is actually a part of the project, which is not guaranteed just because of the precense of a fermenter execution.

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java [hunk 2]
```diff
@@ -67,4 +76,55 @@ protected boolean shouldGenerateStep(Step step, GenerationContext generationCont
...
     }
 
+    /**
+     * Get the appropriate data record package from the given context
+     * @param context the generation context
+     * @return data record package name
+     */
+    private String getPythonDataRecordPackage(GenerationContext context) {
+        File rootDir = context.getExecutionRootDirectory();
+        String sharedDir = rootDir.getPath() + File.separator + rootDir.getName() + "-shared";
```
Comment (epwilkins) [inline foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java]: A: Consider using `getSharedModuleName`

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java (hunk 1 above)
Comment (csun-cpointe) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java]: Yeah.. that was actually my original approach but given the multiple piplelines and changes of split, there could be more module names for validation so instead, I directly go for the profile name

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/python/PythonStep.java [hunk 3]
```diff
@@ -145,9 +145,8 @@ private Set<String> getImports(boolean isImplModule) {
                     importsSet.add(moduleImport.replace("from ",
                             isImplModule ? "from .." : "from ..."));
                 }else{
-                    String rootArtifact = PipelineUtils.deriveLowerSnakeCaseNameFromHyphenatedString(rootArtifactId);
                     importsSet.add(moduleImport.replace("from ",
-                            "from " + rootArtifact + "_data_records."));
+                            "from " + PipelineUtils.deriveLowerSnakeCaseNameFromHyphenatedString(pythonDataRecordPackage) + "."));
```
Comment (epwilkins) [inline foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/python/PythonStep.java:149]: C: What if the data records are generated in-line with the pipeline?

Comment (epwilkins) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/python/PythonStep.java:149]: Ah never mind. I see we have the if check above this. We only execute this logic if it's not in-line generation.

Comment (csun-cpointe) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/python/PythonStep.java:149]: the line approach is already covered by another if block

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java [hunk 4]
```diff
@@ -67,4 +76,55 @@ protected boolean shouldGenerateStep(Step step, GenerationContext generationCont
         return true;
     }
 
+    /**
+     * Get the appropriate data record package from the given context
+     * @param context the generation context
+     * @return data record package name
+     */
+    private String getPythonDataRecordPackage(GenerationContext context) {
```
Comment (epwilkins) [inline foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java:85]: Q/A: Could this also make the determination about whether the data records are in-line with the pipeline, so that the `PythonStep` logic could be simplified?

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java (hunk 1 above)
Comment (epwilkins) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java]: I'm not sure I understand. Wouldn't you just check for the the `DataRecordModule.CORE` name within modules, then check for `DataRecordModule.COMBINED` if core was not present?  Why does the number of modules in `*-shared` matter?

File: foundation/foundation-mda/src/test/java/com/boozallen/aiops/mda/generator/SparkApplicationStep.java [hunk 5]
```diff
@@ -131,4 +159,99 @@ protected void saveFileStores(List<FileStore> fileStores) throws IOException  {
         this.pipeline.setFileStores(fileStores);
         savePipelineToFile(pipeline);
     }
+
+    private void AddPipeline(boolean isPySparkPipeline) throws Exception {
```
Comment (epwilkins) [inline foundation/foundation-mda/src/test/java/com/boozallen/aiops/mda/generator/SparkApplicationStep.java]: A:
```suggestion
    private void addPipeline(boolean isPySparkPipeline) throws Exception {
```

**Review by epwilkins — APPROVED** [review]

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java (hunk 1 above)
Comment (csun-cpointe) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/TargetedPipelineStepPythonGenerator.java]: Discussed offline. To be more clear, will use the full profile name,`aissemble-data-records-separate-module` to check in case of profile name changes.
