### PR TITLE
#141 enable default s3-local deploy template value

### LINKED ISSUE #141: BUG: Manual Actions suppressed by build cache
## Description
When generating code from new MDA models, sometimes manual actions aren't printed because of the Maven build cache.

## Steps to Reproduce
1. Create a new project
    ```
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble'\                       
                       '-DarchetypeArtifactId=foundation-archetype'\
                       '-DarchetypeVersion=1.12.0-SNAPSHOT'\
                       '-DgroupId=org.test'\
                       '-Dpackage=org.test'\
                       '-DprojectGitUrl=test.org/test.git'\
                       '-DprojectName=Test Project'\
                       '-DartifactId=test-141'\
                       && cd test-141
    ```
2. Add a simple data-delivery pipeline  _[example](https://github.com/user-attachments/files/15805736/SimplePipeline.json)_
3. Run `./mvnw clean install` and follow manual actions
4. Repeat until no more actions are printed
5. Run `./mvnw clean install -Dmaven.build.cache.skipCache`

## Expected Behavior
6. All manual actions are still resolved, and no more appear just because the cache is skipped.

## Actual Behavior
6. The build cache has suppressed some manual actions, and so new actions are printed when building with the cache disabled.

## Test Steps
1. Follow the reproduce steps and the result should match the expected behavior
2. Run `tilt up; tilt down`
3. Verify all pipeline can start without any errors

## Additional Context
**Version:** aiSSEMBLE 1.12.0-SNAPSHOT
**"Left-over" actions:**
```
[WARNING] ------------------------------------------------------------------------
[WARNING] Manual Action #1
[WARNING] ------------------------------------------------------------------------
[WARNING] 
In verify-release-deploy/src/main/resources/apps/s3-local/values.yaml:
Remove the empty "[]" from "buckets: []" and include the following content to the list:

    - name: spark-infrastructure
      keys:
      - spark-events/

```

### PR DESCRIPTION
**Pull request by csun-cpointe**
Some manual actions are not added to the template because the template was not existing at that moment. However, this manual action content should be generated to the template by default in the first place instead of generating an empty template and asking user to include the content.

This PR is to address this particular issue for the s3-local template to include missing manual action as default content.

### CODE REVIEW

File: foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/SparkAppKubernetesGenerator.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+     * Usages:
+     * | Target               | Template                                         | Generated File               |
+     * |----------------------|--------------------------------------------------|------------------------------|
+     * | s3LocalValuesFileV2  | deployment/localstack/localstack.values.yaml.vm  | apps/${appName}/values.yaml  |
+     */
+
+    @Override
+    public void generate(GenerationContext context) {
+        VelocityContext vc = this.configureWithoutGeneration(context);
+        vc.put(VelocityProperty.SPARK_APPLICATION_TYPE, true);
```
Comment (epwilkins) [inline foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/SparkAppKubernetesGenerator.java]: S/Q: What happens when the project has both ML and Data pipelines?

Comment (csun-cpointe) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/SparkAppKubernetesGenerator.java]: Because ml pipeline has the s3-local related manual action included in their docker pom generator phase, which is one build cycle early than the data pipeline's s3-local related manual action. Thus, the mlflow will be added as default content in the s3-local template first, then the data pipeline template content will show as manual action after pipeline module build.

Comment (epwilkins) [reply foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/generator/SparkAppKubernetesGenerator.java]: Discussed offline and decided to use the `ModelInstanceRepository` to interrogate the presence of data-flow/machine-learning pipelines, and recombine this logic into a single class that can detect both data and ML pipelines and set the velocity context appropriately.

**Review by epwilkins — APPROVED** [review]
