### PR TITLE
#591 improve archetype test

### LINKED ISSUE #591: Feature: Archetype test improvements
## Description
The archetype test currently relies on a static XML file to determine what content to add to the `test-generator-deploy` POM.  Because the left-over manual action logic has been broken for awhile, this file is woefully out of date. To improve the maintainability, we should just automatically detect and add deployment profiles.  In addition, we should fix the archetype test's manual action detection.

## DOD
- [x] test-archetype.sh successfully updates the deploy POM without the static executions POM
- [x] test-archetype.sh fails the build if a left-over manual action is detected

## Test Strategy/Script
1. Verify `extensions-to-add-to-archetype_test-generator-deploy_pom.xml` is no longer present on dev
2. Verify the latest build succeeded
    - **OTS:** this will be a local build of `mvn clean install -Parchetype-test`
3. Delete the contents of `plugins-to-add-to-archetype_test-generator-deploy_pom.xml`  locally
4. Run the archetype test and verify it fails due to left over manual actions:
    ```sh
    mvn clean install -Parchetype-test
    ```

### PR DESCRIPTION
**Pull request by epwilkins**
The root change is a fix to the detection logic for manual actions that hasn't been functional since manual actions were moved into Fermenter. After fixing that logic, all of the manual actions that were left now had to be handled.
 - For missing deploy executions, I added logic to dynamically detect and add them to the deploy POM
 - For missing deploy plugin, I added a static file that's injected just before the final build
 - For missing alert messaging configuration, I updated the template to include the alert connector configuration by default if alerting is enabled

### CODE REVIEW

File: foundation/foundation-archetype/test-project-archetype.sh [hunk 1]
```diff
@@ -21,27 +22,73 @@ fi
...
+#---
+## Runs maven build and captures any manual actions for adding Fermenter executions to the deploy POM, then updates the
+## deploy POM based on the detected manual actions.
+#---
+function runBuildAndUpdateDeploy {
+  deployInsert="<!-- Add executions for each deployment module -->"
+  outputstart='executions to test-generator-deploy'
+  outputend='\[WARNING\]'
+  # $outputstart match at end ensures the match line isn't captured. NF ensures blank lines aren't captured.
+  execs=$(./mvnw clean install | tee /dev/tty | \
```
Comment (epwilkins) [inline foundation/foundation-archetype/test-project-archetype.sh:82]: I: pipes output through awk so it only starts capturing after the `outputstart` string is detected, and stops capturing after `outputend`. This narrows down the output to just the manual action for adding Fermenter executions to deploy POM. The full logs are still output to stdout via `tee /dev/tty`.

File: foundation/foundation-archetype/test-project-archetype.sh [hunk 2]
```diff
@@ -201,49 +248,41 @@ echo "{
...
+echo -e "\nINFO: updating the test-generator-deploy/pom.xml based on static code as it's hard to predict\n"
+plugins=$(esc < ../../../plugins-to-add-to-archetype_test-generator-deploy_pom.xml)
+sub "s/ *<\/plugins>/$plugins        <\/plugins>/" test-generator-deploy/pom.xml
 
 echo -e "\nINFO: Running full build to check that the build passes w/o any manual actions needed\n"
-./mvnw clean install || { echo -e '\n\n\t**** MAVEN BUILD FAILED ****\n\n' ; exit 1; } > maven-build.log
-buildLog=`cat maven-build.log`
-if [[ $buildLog == *"MANUAL ACTION NEEDED"* ]]; then
+# NOTE: because fermenter results are cached, the build-cache will hide remaining manual actions that were missed in previous steps
+./mvnw clean install -Dmaven.build.cache.skipCache -Dfermenter.display.message.keys=true | tee /dev/tty | awk '/WARNING/ {print}' > maven-build.log \
```
Comment (epwilkins) [inline foundation/foundation-archetype/test-project-archetype.sh:281]: I: again, narrowing the captured output for easier processing. Only captures lines that contain the word `WARNING`, as all manual actions are output as WARN-level logs.

File: foundation/foundation-archetype/test-project-archetype.sh (hunk 1 above)
Comment (aaron-gary) [inline foundation/foundation-archetype/test-project-archetype.sh:82]: Q: is tee a native utility or do users need to install it?

**Review by csun-cpointe — APPROVED** [review]

**Review by aaron-gary — APPROVED** [review]

File: foundation/foundation-archetype/test-project-archetype.sh (hunk 1 above)
Comment (epwilkins) [reply foundation/foundation-archetype/test-project-archetype.sh:82]: It's a non-optional [POSIX util](https://pubs.opengroup.org/onlinepubs/9799919799/)
